version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./server/sentences.txt:/app/sentences.txt
      - ./client/public:/app/public
    environment:
      - NODE_ENV=production
